name: Pipeline N1 - Testes da Pasta 'testes' (Mocha)

on:
  push:
    branches: [main]  # Executa a pipeline em qualquer push na branch main
  pull_request:
    branches: [main]  # Executa a pipeline em qualquer pull request na branch main

jobs:
  testes-n1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Altere conforme a versão do Node do seu projeto

      - name: Instalar dependências
        run: npm install

      - name: Executar testes da pasta 'testes' com Mocha
        run: npx mocha testes/**/*.js
