name: Pipeline N1 - Testes da Pasta 'Trabalho Final'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  testes-n1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Executar testes da pasta 'trabalho final'
        run: npx mocha ./trabalho/**/*.js
